"use client";

import { FormEvent, useState } from "react";
import { Award, Plus, Link2, FileCheck2, Clock3 } from "lucide-react";
import { RoleGate } from "@/features/access/RoleGate";

export default function StudentProfilePage() {
  const [showForm,setShowForm]=useState(false);
  const [sent,setSent]=useState(false);
  const submit=(event:FormEvent)=>{event.preventDefault();setSent(true);setShowForm(false)};
  return <RoleGate allow={["STUDENT"]}><div className="space-y-6">
    <div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><p className="text-sm font-bold text-blue-600 uppercase tracking-wider">Portal del estudiante</p><h2 className="text-3xl font-black text-gray-900 mt-1">Mis certificaciones</h2><p className="text-gray-500 mt-2">Registra una credencial y sigue su estado de validación.</p></div><button onClick={()=>setShowForm(!showForm)} className="flex items-center gap-2 bg-blue-600 text-white px-4 py-2.5 rounded-lg font-bold"><Plus size={18}/>Nueva certificación</button></div>
    {sent&&<div className="bg-emerald-50 border border-emerald-200 text-emerald-800 p-4 rounded-xl">Registro enviado. El validador académico revisará la evidencia.</div>}
    {showForm&&<form onSubmit={submit} className="bg-white rounded-2xl border border-blue-100 p-6 shadow-sm"><h3 className="font-bold text-gray-900 mb-5">Registrar certificación</h3><div className="grid md:grid-cols-2 gap-4">{[["Nombre de la certificación","AWS Certified Cloud Practitioner"],["Entidad emisora","AWS"],["Fecha de emisión","2026-09-09"],["URL de verificación","https://..."]].map(([label,placeholder],i)=><label key={label} className="text-sm font-semibold text-gray-700">{label}<input required type={i===2?"date":"text"} placeholder={placeholder} className="block mt-2 w-full border border-gray-200 rounded-lg px-3 py-2.5 outline-none focus:ring-2 focus:ring-blue-500"/></label>)}</div><label className="block mt-4 text-sm font-semibold text-gray-700">Evidencia PDF opcional<input type="file" accept=".pdf" className="block mt-2 w-full text-sm border border-dashed border-gray-300 rounded-lg p-4"/></label><div className="flex justify-end gap-2 mt-5"><button type="button" onClick={()=>setShowForm(false)} className="px-4 py-2 text-gray-600 font-semibold">Cancelar</button><button className="px-5 py-2 bg-blue-600 text-white rounded-lg font-bold">Enviar a validación</button></div></form>}
    <section className="grid md:grid-cols-3 gap-4"><div className="bg-white p-5 rounded-2xl border border-gray-100"><Award className="text-blue-500"/><p className="text-sm text-gray-500 mt-4">Total registrado</p><p className="text-3xl font-black">2</p></div><div className="bg-white p-5 rounded-2xl border border-gray-100"><FileCheck2 className="text-emerald-500"/><p className="text-sm text-gray-500 mt-4">Validadas</p><p className="text-3xl font-black">1</p></div><div className="bg-white p-5 rounded-2xl border border-gray-100"><Clock3 className="text-amber-500"/><p className="text-sm text-gray-500 mt-4">Pendientes</p><p className="text-3xl font-black">1</p></div></section>
    <section className="bg-white rounded-2xl border border-gray-100 p-6"><h3 className="font-bold text-gray-900 mb-4">Historial</h3><div className="space-y-3"><div className="flex items-center justify-between p-4 bg-gray-50 rounded-xl"><div><p className="font-bold">AWS Cloud Practitioner</p><p className="text-sm text-gray-500 flex gap-1 items-center"><Link2 size={14}/>Credencial pública</p></div><span className="bg-emerald-100 text-emerald-700 px-3 py-1 rounded-full text-xs font-bold">Validada</span></div><div className="flex items-center justify-between p-4 bg-gray-50 rounded-xl"><div><p className="font-bold">Cisco Introduction to Networks</p><p className="text-sm text-gray-500">Evidencia PDF</p></div><span className="bg-amber-100 text-amber-700 px-3 py-1 rounded-full text-xs font-bold">Pendiente</span></div></div></section>
  </div></RoleGate>;
}
